-- Seed sample products for StyleSense demo
-- Run after 001_initial_schema.sql

INSERT INTO public.products (name, brand, category, subcategory, description, image_url, affiliate_url, affiliate_network, price, rating, hair_types, concerns, key_ingredients, is_active) VALUES
('SheaMoisture Raw Shea Butter Moisture Retention Shampoo', 'SheaMoisture', 'shampoo', 'moisturizing', 'Deeply moisturizes and retains moisture for softer hair', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400', 'https://amzn.to/example1', 'Amazon Associates', 12.99, 4.6, ARRAY['curly','coily','wavy'], ARRAY['dryness','damage','frizz'], ARRAY['raw shea butter','argan oil','sea kelp'], true),
('Olaplex No. 4 Bond Maintenance Shampoo', 'Olaplex', 'shampoo', 'repair', 'Repairs broken bonds and strengthens hair from within', 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400', 'https://amzn.to/example2', 'Amazon Associates', 30.00, 4.8, ARRAY['straight','wavy','curly','all'], ARRAY['damage','thinning'], ARRAY['bis-aminopropyl diglycol dimaleate','panthenol'], true),
('Briogeo Scalp Revival Charcoal + Coconut Oil Shampoo', 'Briogeo', 'shampoo', 'clarifying', 'Gently exfoliates scalp while nourishing hair', 'https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=400', 'https://amzn.to/example3', 'Amazon Associates', 42.00, 4.5, ARRAY['all'], ARRAY['oiliness','dandruff'], ARRAY['activated charcoal','coconut oil','tea tree oil'], true),
('Paul Mitchell Tea Tree Special Shampoo', 'Paul Mitchell', 'shampoo', 'balancing', 'Invigorating cleanser that balances scalp moisture', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400', 'https://amzn.to/example4', 'Amazon Associates', 14.00, 4.7, ARRAY['straight','wavy'], ARRAY['oiliness','dandruff'], ARRAY['tea tree oil','peppermint','lavender'], true),
('Schwarzkopf BC Volume Boost Shampoo', 'Schwarzkopf Professional', 'shampoo', 'volumizing', 'Lightweight formula for fine, flat hair with maximum volume', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400', 'https://amzn.to/example20', 'Amazon Associates', 19.00, 4.3, ARRAY['straight','wavy'], ARRAY['thinning'], ARRAY['wheat protein','provitamin B5','creatine'], true),
('Moroccanoil Moisture Repair Conditioner', 'Moroccanoil', 'conditioner', 'repair', 'Reconstructs and detangles damaged hair with argan oil', 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400', 'https://amzn.to/example5', 'Amazon Associates', 34.00, 4.7, ARRAY['wavy','curly','straight'], ARRAY['damage','dryness','frizz'], ARRAY['argan oil','keratin','amino acids'], true),
('Cantu Shea Butter Leave-In Conditioning Repair Cream', 'Cantu', 'conditioner', 'leave-in', 'Deeply moisturizing leave-in for natural hair textures', 'https://images.unsplash.com/photo-1600428853876-fb7a72c2e28b?w=400', 'https://amzn.to/example6', 'Amazon Associates', 8.97, 4.6, ARRAY['curly','coily'], ARRAY['dryness','frizz','damage'], ARRAY['shea butter','coconut oil','honey'], true),
('Kiehl''s Olive Fruit Oil Deeply Repairative Hair Pak', 'Kiehl''s', 'conditioner', 'deep treatment', 'Weekly deep conditioning mask for dry, damaged hair', 'https://images.unsplash.com/photo-1593113630400-ea4288922559?w=400', 'https://amzn.to/example7', 'Amazon Associates', 52.00, 4.5, ARRAY['all'], ARRAY['damage','dryness'], ARRAY['olive oil','avocado oil','lemon oil'], true),
('DevaCurl One Condition Original Daily Cream Conditioner', 'DevaCurl', 'conditioner', 'daily', 'Daily moisture for defining and softening curls', 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400', 'https://amzn.to/example19', 'Amazon Associates', 26.00, 4.5, ARRAY['curly','coily'], ARRAY['dryness','frizz'], ARRAY['botanical extracts','grape seed oil','vitamin E'], true),
('Bumble and Bumble Hairdresser''s Invisible Oil Primer', 'Bumble and Bumble', 'styling', 'primer', 'Weightless heat protection and frizz control', 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400', 'https://amzn.to/example8', 'Amazon Associates', 35.00, 4.7, ARRAY['straight','wavy'], ARRAY['frizz','damage'], ARRAY['baobab oil','maracuja oil','grape seed oil'], true),
('Ouai Wave Spray', 'Ouai', 'styling', 'texture spray', 'Enhances natural wave pattern with beachy texture', 'https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=400', 'https://amzn.to/example9', 'Amazon Associates', 30.00, 4.4, ARRAY['wavy','straight'], ARRAY[]::TEXT[], ARRAY['rice protein','sea salt','cashmere protein'], true),
('Eco Styler Olive Oil Styling Gel', 'Eco Styler', 'styling', 'gel', 'Strong hold gel with nourishing olive oil', 'https://images.unsplash.com/photo-1614345167851-2bbb19c25e93?w=400', 'https://amzn.to/example10', 'Amazon Associates', 7.99, 4.5, ARRAY['curly','coily'], ARRAY['frizz'], ARRAY['olive oil','carbomer','panthenol'], true),
('TIGI Bed Head Self Absorbed Mega Vitamin Conditioner', 'TIGI', 'styling', 'cream', 'Vitamin-enriched styling cream for shine and control', 'https://images.unsplash.com/photo-1561500100-86df7a0c1df2?w=400', 'https://amzn.to/example11', 'Amazon Associates', 18.50, 4.3, ARRAY['all'], ARRAY['frizz','dryness'], ARRAY['vitamin B5','vitamin E','pro-vitamin'], true),
('Olaplex No. 3 Hair Perfector', 'Olaplex', 'treatment', 'bond repair', 'At-home bond-building treatment to strengthen hair', 'https://images.unsplash.com/photo-1617897903246-719242758050?w=400', 'https://amzn.to/example12', 'Amazon Associates', 28.00, 4.8, ARRAY['all'], ARRAY['damage','thinning'], ARRAY['bis-aminopropyl diglycol dimaleate'], true),
('Mielle Organics Rosemary Mint Scalp & Hair Oil', 'Mielle Organics', 'treatment', 'scalp oil', 'Stimulates scalp and strengthens hair follicles', 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400', 'https://amzn.to/example13', 'Amazon Associates', 10.99, 4.6, ARRAY['curly','coily','all'], ARRAY['thinning','damage'], ARRAY['rosemary oil','mint oil','biotin'], true),
('Briogeo B. Well Marula + Tea Tree Scalp Treatment', 'Briogeo', 'treatment', 'scalp treatment', 'Nourishes and balances scalp for healthier hair growth', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400', 'https://amzn.to/example14', 'Amazon Associates', 38.00, 4.4, ARRAY['all'], ARRAY['dandruff','oiliness'], ARRAY['marula oil','tea tree oil','peppermint'], true),
('Redken Extreme Anti-Snap Leave-In Treatment', 'Redken', 'treatment', 'strengthening', 'Prevents breakage and strengthens weak, brittle hair', 'https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=400', 'https://amzn.to/example15', 'Amazon Associates', 23.00, 4.5, ARRAY['all'], ARRAY['damage','thinning'], ARRAY['protein complex','ceramides','amino acids'], true),
('Dyson Airwrap Multi-Styler', 'Dyson', 'tool', 'styler', 'Revolutionary styling tool that uses airflow to style without extreme heat', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400', 'https://amzn.to/example16', 'Amazon Associates', 599.99, 4.7, ARRAY['straight','wavy','curly'], ARRAY['damage','frizz'], ARRAY[]::TEXT[], true),
('Wet Brush Original Detangler', 'Wet Brush', 'tool', 'brush', 'Detangles hair effortlessly without breakage', 'https://images.unsplash.com/photo-1587466280419-21f29b5d7062?w=400', 'https://amzn.to/example17', 'Amazon Associates', 10.99, 4.8, ARRAY['all'], ARRAY['damage'], ARRAY[]::TEXT[], true),
('GHD Platinum+ Professional Hair Straightener', 'GHD', 'tool', 'straightener', 'Smart heat technology for optimal styling temperature', 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400', 'https://amzn.to/example18', 'Amazon Associates', 249.00, 4.7, ARRAY['straight','wavy'], ARRAY['frizz'], ARRAY[]::TEXT[], true);
